[package]
name = "rust-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version = "1.1.0",features = ["full"]}
tokio = {version = "1.35.1",features = ["full"]}
tonic = "0.10.2"
tonic-reflection = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"

[build-dependencies]
tonic-build = "0.10.2"
